services:
  postgres:
    image: postgres:17
    container_name: vehicle_app_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vehicle_app_user
      POSTGRES_PASSWORD: "x9VwQ2mR7Nf4Kp1Z"
      POSTGRES_DB: vehicle_app_db
    ports:
      - "5444:5432"
    volumes:
      - vehicle_app_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vehicle_app_user -d vehicle_app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  vehicle_app_pgdata:
